### PR TITLE
Split adapters into separate tests for better maintainability

### PR DESCRIPTION
**Pull request by stnguyen90**
By splitting the adapter tests out, each test won't impact any other tests.

### CODE REVIEW

**Comment by stnguyen90** [comment]
@christyjacob4, did our `TEST_RAYGUN_KEY` key expire or something?

**Comment by christyjacob4** [comment]
@stnguyen90 yes I have updated it now

**Comment by christyjacob4** [comment]
Also the sentry constructor was updated so please sync your PR with `main`
https://github.com/utopia-php/logger/pull/29

**Comment by stnguyen90** [comment]
@christyjacob4, done.

**Review by christyjacob4 — APPROVED** [review]

**Pull request merged**
